spring.application.name=app
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}

conection-string.blob.storage=${CONECTION_STRING_BLOB_STORAGE}
container.name.customer=${CONTAINER.NAME.CUSTOMER}
container.name.order=${CONTAINER.NAME.ORDER}
